openshift_cluster_content:
- object: deployments
  content:
  - name: "deploy dvl environment"
    template: "{{ inventory_dir }}/../../.openshift/templates/alldeploy/deploy.yml"
    params: "{{ inventory_dir }}/../../.openshift/params/dvl/alldeploy/deploy-dvlb"
- object: route
  content:
  - name: "create route"
    template: "{{ inventory_dir }}/../../.openshift/templates/alldeploy/dvlb-tls-route.yml"
    params: "{{ inventory_dir }}/../../.openshift/params/dvl/alldeploy/route-dvlb"