apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: resomnipro-websockerserver
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${APPLICATION_NAME}
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}
  spec:
    failedBuildsHistoryLimit: 5 #Number of failed builds to keep
    nodeSelector: null # Limits which nodes pod will be placed in
    output:
      to:
        kind: ImageStreamTag # Docker Image Tag
        name: ${APPLICATION_NAME}:${TAG}
    postCommit: {} 
    resources: {} 
    runPolicy: Serial # Order that builds should run
    source:
      binary: {}
      type: Binary # Build type. Binary builds stream content from local file system to builder
    strategy:
      sourceStrategy: #
        from:
          kind: ImageStreamTag
          name: ${IMAGE_STREAM_TAG_NAME}
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    successfulBuildsHistoryLimit: 5
  status:
    lastVersion: 0
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-demopipeline
    namespace: ${NAMESPACE}
  spec:
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      sourceSecret:
        name: git-secret
      contextDir: ${CONTEXT_DIR} 
    triggers:
    - type: ConfigChange
    - gitlab:
        secretReference:
          name: gitlabsecret
      type: GitLab
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${PIPELINE_SCRIPT}
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
- description: The namespace to deploy into
  name: NAMESPACE
  required: true
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  required: true
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  value: 
- description: Path within Git project pointing to the pipeline run script
  name: PIPELINE_SCRIPT
  required: true
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Image stream tag for the image you'd like to use to build the application
  name: IMAGE_STREAM_TAG_NAME
  required: true
  value: delta-openjdk18-openshift:1.6
- description: Image tag
  name: TAG
  required: true
  value: latest