apiVersion: v1
kind: Template
labels:
  template: git-secret
metadata:
  annotations:
    description: git secret for credentials
    tags: secret
    version: 1.0.0
  name: git-secret
  namespace: ${NAMESPACE}
objects:
- apiVersion: v1
  data: null
  stringData:
    ssh-privatekey: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIJJwIBAAKCAgEAv6aez3CvDF5kcxWO5VIxYe6fx33gDLs9Xcc+CBwA1ZZMhmG1
      Ij/IUtl6za5VlZY/DtGokUgp6uGxjQLeR5bJK4dd1WoVFaPqqlkpCqzC53iGUGQ3
      3CuMCK08iKpFlZan0uEg7AaBNUvxBxGdie8Hh7OcrC4jP5Q8h76BHIBxceWZ2HWt
      G6gNbdA4WGSA2B+yip1gVJHR89BoD1z/Z3NwWlVScAe0jqe1JGXw/xxqT9aEFNJo
      Rg8A2A/hEGjC0Lkbt7mrNmR62I6DGP04OQdNJT8I+jf7/AKQHHj55WQTbrqIVDNt
      w02lk/CDoMG3KBWXmCjBYeu003DGKVcQRAgCALwQmeVoLbZ7j7PhsCs84eLW80OZ
      qFgIeijJG+iEtpNbnybU9omyof5iQC5OWk+tSQ+ZwxW74AwFopAitA3mx44z7DyL
      ZYSqJCLfIG+Fhgqw9wrLT5RjbDNA2m1X2Y+pUFgMugqJGAT9/rz6Fnj3g/T8+Gcu
      3F9JcvB1g74I+bHlak0svEH6k5aqsLW4KVkXwu+rTgR3cS5VE3TAuFcLwVmkpF2I
      h7rnsJ5OClVScCZIt1sBYrrWG5/tZXn0W/CFY1DNeRP+DizCVU0sVanUbBPUCb1n
      K2l/22KpcqixdD5F9TSgju4gL3EuTDvmAjz8wHBbaCzLAAMaRw0nN4blOEUCAwEA
      AQKCAgATsrx/9cUIMGuCqKSXTWtl9XDWwElXBae5C9GEY9xyF5Cl/0Tu0D92xIOq
      wFBrn5W7oDEDPbeRPMFTDQhrs0PaBX/Pf6fLIZ3tBF0Di948jFbBzIsxRgiOm7+t
      DFM6nNGDC0CnAcQmBjgv0c+vbbIIcJ2Z1OQqlMHj8eCzXUBLxJ2bcfzo6sz2jIA+
      FZZooFlpheNwzcwWk0UezyAxMdxKbJqciS41u2cS5qdukS0cJ6BLw5SUHtanXnpz
      hVEAwwXmTF8cqBc4Su2Ok/hDZEy5l1EE5twvetP1GToWKcMVjnaUsPSHLmPmYMIm
      s8JvjEiYixfVSLS9RsoXVauGUoxh+PyKD+C68KVs1dPqX1Xu/PAWbEYvlkJOXbq2
      4e4fzqNBU1SU086BY3sLX99XYzqxuZQu1HcrSkb+6hUF4v6lNKDAfBurKYUjdzs8
      rTKZu1lPmf7URLelWvdcWz+jcNajEB/GQ+vQUQhMuQDrEW9x2BuxmR1vZ7yApu+Y
      WUa6z69iiIeIRfOSTtB7ALTBWaaZpNz6xoCQmcuBHBRdajik9bKp2MYTBsvuTAzQ
      2d7QbNFPfWUqXImGAquutDPNdfUcg1pE+wy+qPDGHpRKcCV4Zuua1Z8jk9qgZ2c8
      8S+1QG4QjIuga5pOk907rmWlb1JSgsjWzbepvssm/POELzcqAQKCAQEA/gH86sRt
      zGdzaEnEHsaBewPHq+XDC5Ja2Dr99IMLyHgyWJRbeRN4UGuC0plzZxzNJSAPBn19
      FzL+YsMqR5YiWh6Ogpayvz17976vTxVRCZVWUBj9ZK1Mquv/+EDUdQS3RXUTsYvG
      1PJahj/N3EocGXK+jqKsRn6D5Sjuz7S2GVkoJWzUJbKD/kdRLm5yMarpnTQc4gm0
      Is6qUxoEXZpmsvBXZpUnphT0TytuTrIVoeG3xBzqQ2LvIQXLSqtgvwcv2PkJNolp
      tpcfpM8OVnhrzb2dhfMZ7Wg+55qeE3X0Vf8yX/3sWAmlY2Jx+CPActylNms4FdyH
      5yKB89eV3he+WQKCAQEAwSdtr2+m7lI64SbP9CCzmlSQEDsLvhmE3Kz0H5kDFixl
      QiufAK9iJ7bvaeSqAM7tdrdoVFYcXVM0QBLr+m/0IQG2n/RsCYR8hmMuhp9fpcfn
      v57tuBNiUlZmNzfn5fcl46mmNQi1o9xL/kQpgr0XTfOpjJMpNiLJNnaQ8gM8DiCL
      boMRjiZNh0GOTiNUGSMlgQkk1zRPMpcFuhH4vZ79rbYkZZ+e1QPL0NdTaSW9MQer
      uWA5KXfxDIWmWcFRK1CAXz+/7c7gce8LuZpaAeFz8gVUdH1yqcQknNHbj0dqnpK7
      vRDP6s+dlPLJZ5W4yJ1M5Pv8J2hoqXajWMKDwoTDzQKCAQBR02IeXtjgGBNdbSX4
      pAniDv2rqoCCocsSDS7yLaUGF3JghqpQ/qyre3bRUQ2UEfskEofEl3hMmOjJ+AUO
      upamYWGXP+SlJrFgxdTDrSJF7A26D9LRM+KWzR/QYVIPwE0p2uVVNKoAv3HZ/YPb
      iyQyLnykhlLpAqiKkf0cfCKNV+NO6xgMbM2IhIDqbDntNhm7wqXrSyT0cY785kyx
      uqOK0VHWggYbwnRRbLRENaoyU/xW+Nmei6htAujSTRMFdtM7Gj6Viv67C0PuW6VK
      xdA0nvi3xfB8QjDBe1Wg/0aOzX703V/dnH3i3jvIq/u7BMlUFoYixMAi/ULPwotM
      2GlBAoIBAFZK5i7to9dvN0zliRxZC8RUKTSHHJzmS7xHLJ19P6rFVMu2L0ggEqsJ
      iHZ3qRfJWr+h+uNKwUtUY9CIY5K0N44TdOKLUUUDQprLbrrIMvQelkO+nheR2WhN
      n0bmHB1aSDwoy89/v56gSfcjvqPhFKtHw6TBDjVYXyqM1/63QTpSgdhyiAJIzHQz
      7n6sO+MrF5NJYYMfpI5GeFGDu+wDPvQ/no0kPdKO6py3xlUAfkCMW8Tq3z7Ojgt5
      HjOVMU03ntJu6bE1roJYOJXIBpQ2hBVJGk0cyoBb17uT6hJd5p1HksZJ34nZDV7B
      BQfZFP/TfsoCZcm5VKD5FssNw83AgLUCggEARVAAJG0ek5gg3qDAMKQJsNpoFQA4
      SPguE8EuqyUdyrxsqfia5kEYB+IcuuqZqt7d+0VuT+y14jWjSJHK9BkTTsX4XjVd
      g4XU0dlsng7dw64kuMT7SCUoajU+DW7J8aAh3c+a9Lf6Oh1mEW+/H/HTdmHy/LOq
      qC+mR+dxofHr+J7NNfQbY9xjQGSZRy9Pym+Eo6cV77hLDcx7t4Y6YA8dnk8xQpRV
      1QHeQ3Qj263heDQgzQqrTt6RRD9V/Q+2KwIE+SrBfs2/H4vC3xUuhSFpXmMsD0Ka
      rqWsvGvdkKjBx6No0b4huCT4+jTSKFRPzMJLwrgjnYpfKwxym6fZJY/BFw==
      -----END RSA PRIVATE KEY-----
  kind: Secret
  metadata:
    name: git-secret
    namespace: ${NAMESPACE}
  type: kubernetes.io/ssh-auth
parameters:
- description: The namespace to create secret
  name: NAMESPACE
  required: true